# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder tags

# Attribute name
nameFrom: name

# Model Class name
modelClass: Waka\Segator\Models\Tag

# Toolbar widget configuration
#toolbar:
    # Partial for toolbar buttons
    # buttons: reorder_toolbar